### PR TITLE
Change colors (again)

### PR DESCRIPTION
**Pull request by emidoan**
## Summary
Changed colors (again) to match web accessibility standards. 

## Future Followup
idk what im doing 👍🏼

### CODE REVIEW

**Comment by ChaseC99** [comment]
Can you screenshots of the changes so we don't have to run the code locally?

**Comment by emidoan** [comment]
> Can you screenshots of the changes so we don't have to run the code locally?

Screen Shot 2022-02-17 at 8 18 10 PM

**Review by ChaseC99 — APPROVED** [review]
very nice colors 😍

**Comment by nathantoannguyen** [comment]
Love love!

**Pull request merged**
