### PR TITLE
Hid Sponsors

### LINKED ISSUE #126: Hide "Sponsors" Section
Talk to corporate to see what they want to do with this section. They may want to hide it or just change it to "Past Sponsors".

### PR DESCRIPTION
**Pull request by allisl7**
## Summary
I hid the sponsor section.

## Test Plan
Ran npm & checked localhost website to see changes made

## Issue(s)
Closes #126

## Future Followup - waiting for Corporate to respond what they want to do with the Sponsors section, but for now I hid this section.

### CODE REVIEW

**Review by nathantoannguyen — COMMENTED** [review]
Looks good if we want to hide these sponsors for now, but I am insecure so I will let someone else approve this :D

**Review by ChaseC99 — CHANGES_REQUESTED** [review]
Per you last message in Slack, we should probably just update the header to "Past Sponsors" now instead of hiding it.

**Comment by nathantoannguyen** [comment]
The sponsors title is currently an image. Is it possible to have a new header image with "Past Sponsors" that has the same font? @emidoan

**Comment by emidoan** [comment]
> The sponsors title is currently an image. Is it possible to have a new header image with "Past Sponsors" that has the same font? @emidoan And will we have a new section for our sponsors this year?

Uploaded to Assets folder: https://drive.google.com/drive/u/0/folders/1c_AEikfgzhjuCdqKbqskcl4G1NHfth6u

**Comment by nathantoannguyen** [comment]
Closing pr because I created a new one with intended changes

**Pull request closed without merging**
